services:

  db:
    container_name: postgresql_db
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - 5050:80
    depends_on:
      - db

  smtp-service:
    container_name: smtp
    image: axllent/mailpit
    ports:
      - "8025:8025"
      - "1025:1025"
    restart: unless-stopped

  app:
    container_name: e_store_app
    build:
      context: .
      dockerfile: e_store/Dockerfile
    volumes:
      - .:/app
    environment:
      - PORT=8000
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: always
