[tool.poetry]
name = "e-store"
version = "0.1.0"
description = ""
authors = ["Yossef-Dawoad <yossefdawoad15@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = { extras = ["all"], version = "^0.115.0" }
psycopg = { extras = ["binary", "pool"], version = "^3.2.2" }
sqlalchemy = "^2.0.35"
pydantic = { extras = ["email"], version = "^2.9.2" }
sqlmodel = "^0.0.22"
alembic = "^1.13.2"
passlib = { extras = ["argon2"], version = "^1.7.4" }
pyjwt = { extras = ["crypto"], version = "^2.9.0" }
python-multipart = "^0.0.10"
celery = { extras = ["redis"], version = "^5.4.0" }
slowapi = "^0.1.9"
flower = "^2.0.1"
fastapi-mail = "^1.4.1"
jinja2 = "^3.1.4"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.3"
ruff = "^0.6.6"
httpx = "^0.27.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
lint.select = ["E4", "E7", "E9", "F"]
lint.extend-select = [
    'C4',
    "F",       # pyflakes
    "E",       # Errors
    "W",       # warnnings
    "RUF",     # Ruff-specific rules
    "PERF",    #PREFlint
    "PL",      # PYLINT
    "UP",      # pyupgrade
    'SIM',     #sim for code simplification
    'TCH',     #tch for type checking
    'F707',    # Syntax error in forward annotation
    'I001',    # Import block is un-sorted or un-formatted
    'I002',    # Missing required import:
    'COM',     # FLAKE COMMA
    'ANN',     # flake8-annotations
    'PYI052',  #Need type annotation for
    'DTZ',     #FLAKE datetime
    'ASYNC',   #FLAKE ASYNC
    'PLE1700',
]
show-fixes = true
target-version = "py310"
line-length = 110
lint.ignore = [
    'E501',
    'SIM115',
    'ANN101',
    "UP007",
    "E701",
    "D",
    "CPY001",
    'COM812',
]
extend-exclude = ['alembic', 'migrations']

# [tool.ruff.lint]
# select = ["ALL"]
# ignore = ["D", "CPY001"]
