"""user has disabled & username

Revision ID: 2550f97a54cc
Revises: 1534611be4f7
Create Date: 2024-06-02 19:33:08.474550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # NEW


# revision identifiers, used by Alembic.
revision: str = '2550f97a54cc'
down_revision: Union[str, None] = '1534611be4f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'name', nullable=False, new_column_name='username')
    op.add_column('user', sa.Column('disabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'username', new_column_name='name', nullable=False)
    op.drop_column('user', 'disabled')
    # ### end Alembic commands ###
