"""user has disabled & username

Revision ID: 2550f97a54cc
Revises: 1534611be4f7
Create Date: 2024-06-02 19:33:08.474550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # NEW


# revision identifiers, used by Alembic.
revision: str = '2550f97a54cc'
down_revision: Union[str, None] = '1534611be4f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('user', sa.Column('disabled', sa.Boolean(), nullable=True))
    op.drop_index('ix_user_name', table_name='user')
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.create_index('ix_user_name', 'user', ['name'], unique=False)
    op.drop_column('user', 'disabled')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
