"""add total field for cart tables

Revision ID: 32d5b160eb40
Revises: 2550f97a54cc
Create Date: 2024-08-02 21:42:09.293261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # NEW


# revision identifiers, used by Alembic.
revision: str = '32d5b160eb40'
down_revision: Union[str, None] = '2550f97a54cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('total_amount', sa.Numeric(scale=2), nullable=False, server_default='0.0'))
    op.add_column('cartitem', sa.Column('subtotal', sa.Numeric(scale=2), nullable=False, server_default='0.0'))
    op.drop_index('ix_user_name', table_name='user')
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.create_index('ix_user_name', 'user', ['username'], unique=False)
    op.drop_column('cartitem', 'subtotal')
    op.drop_column('cart', 'total_amount')
    # ### end Alembic commands ###
