"""adding time_stamp props

Revision ID: f706cd0b0ab1
Revises: 32d5b160eb40
Create Date: 2024-09-22 14:29:13.262431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # NEW


# revision identifiers, used by Alembic.
revision: str = 'f706cd0b0ab1'
down_revision: Union[str, None] = '32d5b160eb40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # TODO Handel defualt not Null Issue for created_at 
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    op.alter_column('user', 'created_at', server_default=None)
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('verified_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'verified_at')
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    # ### end Alembic commands ###
